version: "3.8"
services:
  jenkins-controller:
    build: .
    container_name: jenkins-controller
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=<docker_host> # For agents
      - DOCKER_TLS_VERIFY=1
      - JENKINS_ADMIN_ID=<admin_user>
      - JENKINS_ADMIN_PASSWORD=<adminPassword>
      - JENKINS_GITHUB_SSH=<yourPrivateKey> # For Github connection
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  docker-dind: ## Agents of the Jenkins
    command: --storage-driver=overlay2
    container_name: jenkins-docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    image: docker:dind
    links:
      - "jenkins-controller:docker"
    networks:
      - jenkins
    ports:
      - "2376:2376"
    privileged: true
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

networks:
  jenkins:
    name: jenkins

volumes:
  jenkins-data:
  jenkins-docker-certs:
